### ISSUE TITLE
DRand stats are inactive

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#19]
The dashboard says that for the last 2 months there were no DRand stats, and for 9 days no tty-ping. Is that normal? Should the DRand stats be removed?

**Comment by tharvik** [comment]
So, there was some issues, now fixed in the repo. There is another one: the TTY activity fails to work as there no more space to store the logs. Initially, it was made to have a full log of what happened on drand.c4dt.org in case of attack (as required by drand's operator guidelines). Is there a better way to store theses logs? Or do I regularly remove the oldest entries?

**Comment by ineiti** [comment]
Do the operator guidelines say something about the duration you have to keep the logs? 1 month looks like a good value to me - what do you think?

With regard to the space: is this on switch.c4dt.org?

**Comment by tharvik** [comment]
> Do the operator guidelines say something about the duration you have to keep the logs?

Nope, no duration is stated.

> 1 month looks like a good value to me - what do you think?

Let's go with a month then.

> With regard to the space: is this on switch.c4dt.org?

Correct, in `/dev/vdb1` mounted at `/home/stats/data`.
