### ISSUE TITLE
Adjust DRand activities

### ISSUE THREAD

**Issue by ineiti** [c4dt/stats#50]
The DRand activities often go over the limit of 150 l/m:

https://stats.c4dt.org/d/5OE0NY7Vz/drand?tab=alert&viewPanel=4&orgId=1&from=1664221703181&to=1664223479639

I propose to:
- [ ] check if this is because there is more traffic, and so it's something benign
- [ ] if yes to above, increase the limit to 300 l/m or perhaps even 400 l/m

**Comment by tharvik** [comment]
hum, so yeah, ansible does indeed uses of lot the TTY. it does so every time `ansible-config` is deployed by webhook.

I wanted this graph to be hyper-sensitive, in order to detect pretty much any out-of-the-ordinary activity. we can't have that and ansible, so yeah, 300 c/m. if someone does a pretty bad attack and actually fill the logs more than ansible, we would detect it, but yeah, hopefully, it won't happen.

**Comment by ineiti** [comment]
The link to the stats I sent above has many peaks above 150 c/m in a short interval - I don't think it's all ansible deployments.

Also, could you check the actual logs? They seem to have increased a bit over the past week or so.

**Comment by tharvik** [comment]
> The link to the stats I sent above has many peaks above 150 c/m in a short interval - I don't think it's all ansible deployments.

it seems that chromium was outdated and new AppArmor settings disallow some of its access; trying to workaround 

> Also, could you check the actual logs? They seem to have increased a bit over the past week or so.

I did. updating the OS added/changed a bunch of TTY activity

**Comment by tharvik** [comment]
> > The link to the stats I sent above has many peaks above 150 c/m in a short interval - I don't think it's all ansible deployments.
> 
> it seems that chromium was outdated and new AppArmor settings disallow some of its access; trying to workaround

~fix in https://github.com/c4dt/ansible-config/pull/102
